# Generated by Django 3.0.3 on 2020-03-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_written',
        ),
    ]
